### ISSUE TITLE
override --size in cluster.yaml when --size-low-pri is used a param (and vice versa)

### ISSUE THREAD

**Issue by jiata** [Azure/aztk#127]

**Comment by jafreck** [comment]
This is a UX issue and it's unclear what is more transparent to the user. If size or size-low-pri is specified in the config file, and the user passes the other on the command line, the current fucntionality is to throw an error, saying that you cannot specify both size and size-low-pri. This might be unclear to users as they intend for the command line size to be the truth. However, it is also unclear for a user to specify a certain type of size in the config file, and then have a command line parameter override a different setting.

@paselem  We discussed this Friday and I think decided that throwing an error to alert the user of the bad configuration was the best way to go.

**Comment by jiata** [comment]
for users who are just starting with aztk, they may not know about cluster.yaml file, so the fact that `--size` is specified would be confusing to them. 

This will be the likely actions of the brand new user:
1. downloads/setups aztk
2. runs `aztk spark init`
3. adds secrets
4. creates a cluster and wants to use low priority vms 

I doubt the brand new user will dive into non-mandatory cluster settings

**Comment by jafreck** [comment]
So you think the cluster.yaml should come with no preconfigured cluster size or size-low-pri?

This would change the workflow from:
1. clone repo
2. `pip install -r requirements.txt`
3. `pip insatll -e .`
4. `aztk spark init`
5. `aztk spark cluster create --id <id>`

to:
1. clone repo
2. `pip install -r requirements.txt`
3. `pip insatll -e .`
4. `aztk spark init`
5. `aztk spark cluster create --id <id> --vm-size <vm-size>`

**Comment by jiata** [comment]
i think it should come with preconfigured cluster size (size: 2) 

However, when a user specifies a size on the command line, whether it is low pri or dedicated, it should override it.
