### ISSUE TITLE
add instructions for getting secrets from batch/storage via az cli

### ISSUE THREAD

**Issue by jiata** [Azure/aztk#147]

**Comment by jafreck** [comment]
Do you think the CLI should just link to the repo's docs on how to do this, or should it actually give instructions itself?

**Comment by jiata** [comment]
I think putting it in the docs is sufficient. SOmething like:

1) install cli
2) az login
3) the get batch keys command
4) the get storage keys command

But if we're gonna do this, we might as well provide instructions on how to *create* batch and storage on the cli too

**Comment by jafreck** [comment]
Are you saying we have login and batch/storage key retrieval functionality on the command line? 

Or just instructions on how to do those things?

**Comment by paselem** [comment]
I think he means just showing how to do it using the Azure Command Line (not implement it ourselves). @jiata - I think we should not ask users to install the CLI, but probably defer to the Portal Cloud Shell instead since it should be pretty quick and painless.

**Comment by akzaidi** [comment]
[This](https://github.com/akzaidi/batch-ml/blob/master/1-getting-started.md) might be helpful. It lists some instructions on using the CLI to create storage and batch accounts, and uses jq to pull out the keys into variables. 

It'd be really cool if we could use `sed` to directly modify the `secrets.json` file with the variables we pull out of the jq queries.
