### ISSUE TITLE
aztk spark cluster submit doesn't work

### ISSUE THREAD

**Issue by robertoNdams** [Azure/aztk#151]
```bash
(envs/python35)  % aztk spark cluster submit --id test_aztk --name pipy examples/src/main/python/pi.py 1000                                                                                                                                              
-------------------------------------------
Spark cluster id:        test_aztk
Spark app name:          pipy
Wait for app completion: True
Application:             examples/src/main/python/pi.py
Application arguments:   ['1000']
-------------------------------------------
Task is waiting to be scheduled.
Task is waiting to be scheduled.
/usr/bin/python3: can't open file '/batch/workitems/test_aztk/job-1/pipy/wd/Users/ges/Work/Trial/azure/data/azuretk/aztk/examples/src/main/python/pi.py': [Errno 2] No such file or directory
Spark application is completed!
```

**Comment by davidgreenshtein** [comment]
I have exactly the same issue, this is a blocker to use aztk, please assist.

**Comment by timotheeguerin** [comment]
Hhm, I wonder if this has to do with it mapping the absolute path on the VM.
Can you in the meantime go on the portal or batchlabs or ssh on the node to see what this wd contains and if this file is at the wrong place or not.

I'll take a look at it today.

**Comment by timotheeguerin** [comment]
actually I was able to repo on OSX

**Comment by paselem** [comment]
@timotheeguerin 
This looks weird to me: 

/usr/bin/python3: can't open file **'/batch/workitems/test_aztk/...'**


Shouldn't the path be /mnt/batch/tasks/workitems/... ? I can't remember the path is remapped once the container is loaded...

**Comment by jiata** [comment]
I dont think that's the issue @paselem . i think test_aztk is just the pool name. I'm able to repro on OSX

![screen shot 2017-10-06 at 8 38 50 am](https://user-images.githubusercontent.com/16616215/31286035-cf5bb9a2-aa71-11e7-9e75-253f34aeec06.png)

**Comment by robertoNdams** [comment]
The same errors occurs both on OSX and ubuntu (xenial):
```bash
ubuntu@ubuntu-xenial:~/azuretk$ aztk spark cluster submit --id test_aztk --name pipy200 aztk/examples/src/main/python/pi.py 1000
-------------------------------------------
Spark cluster id:        test_aztk
Spark app name:          pipy200
Wait for app completion: True
Application:             aztk/examples/src/main/python/pi.py
Application arguments:   ['1000']
-------------------------------------------
Task is waiting to be scheduled.
Task is waiting to be scheduled.
Output file hasn't been created yet
/usr/bin/python3: can't open file '/batch/workitems/test_aztk/job-1/pipy200/wd/home/ubuntu/azuretk/aztk/examples/src/main/python/pi.py': [Errno 2] No such file or directory
Spark application is completed!
```

**Comment by paselem** [comment]
@jiata - I didn't mean the test_aztk is the issue, but rather the initial path. By default on Batch it is /mnt/batch/tasks, but here the path is /batch/workitems/. That looks strange unless were are doing some remapping of /mnt/batch/tasks -> /batch/. If we are, we should probably remove that unless there is a very compelling reason to do so.

**Comment by jafreck** [comment]
We do remap /mnt/batch/tasks to /batch, [here](https://github.com/Azure/aztk/blob/dd5a5c938a24fb920c0c20e2089f4b48d0c992e7/aztk/clusterlib.py#L66). Not entirely sure why that is done except for convenience.

**Comment by timotheeguerin** [comment]
just merged a fix can you guys pull and try again and let us know if it still fails

**Comment by davidgreenshtein** [comment]
this issue fixed, thanks.
Now this command does not work anymore, maybe it is related

`aztk spark cluster ssh --id aztk_test_cluster --username spark

bash: sudo docker exec -it spark /bin/bash: No such file or directory`

**Comment by paselem** [comment]
#157

**Comment by jafreck** [comment]
@davidgreenshtein Just put in a PR to fix your issue. #157
