### ISSUE TITLE
Support building custom Dockerfiles on the node

### ISSUE THREAD

**Issue by jafreck** [Azure/aztk#183]
Currently we force users who want to use a custom container to build an image and upload it to Docker Hub. 

Users should have the option to just pass their Dockerfile and have the container built on the node at runtime.

This would also be great for development/testing.

**Comment by darylmsft** [comment]
Strictly speaking this is not universally true.  Windows based containers do not require a custom image.

Licensing issues block the flow you describe but we are working on it.

**Comment by jiata** [comment]
has there been a specific customer ask for this? (just curious)

**Comment by jafreck** [comment]
no specific ask, just a nice-to-have I was thinking about.
