### ISSUE TITLE
SSH Tunnel for jobui failed to open in localhost

### ISSUE THREAD

**Issue by audac1ty** [Azure/aztk#228]
The ssh tunnel for port 4040 currently results in a connection refused error.

**Comment by audac1ty** [comment]
Made a workaround for this:

- Root use of port 4040 was for access to the job ui and log files.

- Workaround is to use the aztk spark cluster app-logs command within the CLI to obtain the logs for a job.

**Comment by paselem** [comment]
@audac1ty - This is actually part of the Spark Jobs UI design. If there are no jobs running, then the :4040 port doesn't render anything.

The way you worked around this is one of the two supported ways. The second way would be to enable the history server in your spark-defaults.conf. Set the history server log path to something local like file://tmp/spark-logs

**Comment by audac1ty** [comment]
Yeah that was assumed after some investigation on my part, resolved fairly easily after acknowledgement
