### ISSUE TITLE
Comment out default value for docker-repo

### ISSUE THREAD

**Issue by jafreck** [Azure/aztk#254]
https://github.com/Azure/aztk/blob/c12ecebad239b9d01604f81ae57e38738fa36237/config/cluster.yaml#L18

This value should be commented out. Logic is already in place to select a default docker-repo, which this setting will override. This makes the default experience broken for GPUs.

If a user just runs `aztk spark init` and `aztk spark create cluster --vm-size nc6`, the image downloaded will not be a GPU image because the value in cluster.yaml overrides the logic that selects the gpu image.

**Comment by jiata** [comment]
i think as part of this issue, we should also add a note in the docs for GPU that if you do not specify a docker repo and you select a gpu vm size, we will pull from the aztk/gpu repo by default. But there are is also the aztk/python....-gpu repo too.

**Comment by jafreck** [comment]
(GPU section of the docs does cover that.) [https://github.com/Azure/aztk/blob/master/docs/60-gpu.md] However, we should probably note this again [here](https://github.com/Azure/aztk/blob/master/docs/12-docker-image.md) and [here](https://github.com/Azure/aztk/blob/master/docker-image/README.md).

**Comment by jiata** [comment]
doesnt look like the GPU section covers it. I mean to explicitly state "If you do not specify a docker repo and you select a gpu enabled vm size, AZTK will automatically pull from the aztk/gpu:xyz repo."

**Comment by jafreck** [comment]
Closing since fixed by #358
