### ISSUE TITLE
global configuration files created with aztk spark init --global are not found in other dirs

### ISSUE THREAD

**Issue by willferreira** [Azure/aztk#260]
When I run:

aztk spark init --global 

a .aztk/ directory is correctly created in my $HOME dir. I edit the secrets.yaml file to configure keys, account names etc. But when I try and create a cluster in another location using the command:

aztk spark cluster create --id spark --vm-size standard_a2 --size 4

I get the message:

_Batch account key is not set in secrets.yaml config_

The workaround is to copy the directory ./aztk/ in my $HOME dir to the location I'm trying to create the cluster. I'm using the latest release of aztk with python 3.6.2 on MacOS High Sierra 10.13.1 

conda list gives:

azure-batch               3.0.0
azure-common          1.1.8
azure-nspkg              2.0.0 
azure-storage           0.33.0

**Comment by jafreck** [comment]
I believe the wrong file path was being used to read the global secrets file. Just put out a PR to fix it. Nice catch!
