### ISSUE TITLE
on cluster created with `--wait`, there is no feedback from the cli, and it looks like it is hanging... 

### ISSUE THREAD

**Issue by jiata** [Azure/aztk#261]
Currently, it looks like this until the cluster is created and *completely* ready.
![screen shot 2017-12-09 at 5 04 57 pm](https://user-images.githubusercontent.com/16616215/33801042-1b8432e6-dd03-11e7-9e11-5ec340188b8b.png)

For now, if --wait is true, then we should just add a simple "please wait while your cluster is being provisioned" setting.

In the future, we should poll for pool status and provide progress feedback to the user.

**Comment by jafreck** [comment]
What would be really nice is a progress bar. But that would be a large change. We could just add the text like you said and a spinner.
