### ISSUE TITLE
R image: mismatch between naming in docker-image/readme.md and docker hub repo

### ISSUE THREAD

**Issue by jiata** [Azure/aztk#262]
This: 
https://github.com/Azure/aztk/blob/docs/update/docker-image/README.md#matrix-of-supported-container-images 
doesnt match this:
https://hub.docker.com/r/aztk/r-base/tags/ 

@brnleehng for the python images, we use the convention "aztk/python:spark2.2.0-python3.6.2-base" 

Should we do the same with R images? so it would look like this: "aztk/r-base:spark2.2.0-r3.4.2-base"

Eventually we would also have "aztk/r-base:spark2.2.0-r3.4.2-gpu"

**Comment by jafreck** [comment]
I just changed the dockerhub builds to reflect the tag convention you noted.

So the images that we will have under aztk/r-base will be:
- spark2.2.0-r3.4.1-base
- spark2.1.0-r3.4.1-base
- spark1.6.3-r3.4.1-base

**Comment by jafreck** [comment]
Closing since rebuilding on Dockerhub makes this no longer an issue.
