### ISSUE TITLE
Failed task prevents same task being (re)submitted

### ISSUE THREAD

**Issue by willferreira** [Azure/aztk#270]
I can't re-submit a task after it has just failed, without deleting the old task (in the portal). Maybe this is expected behaviour?

**Comment by jafreck** [comment]
Thanks for logging the issue, but unfortunately this is expected behavior for now. There is a limitation for app (task) names that prevents reuse -- all must be unique.

We are exploring options on how to get around this limitation.

**Comment by willferreira** [comment]
Thanks.
