### ISSUE TITLE
Getting: Error response from daemon: Container <long id> is not running

### ISSUE THREAD

**Issue by willferreira** [Azure/aztk#285]
This error message is being returned when I try and submit a spark job to a newly created cluster. Cluster created with:

`aztk spark cluster create --id sparky --vm-size standard_a2 --size 1 --docker-repo aztk/python:spark2.2.0-python3.6.2-base`

Job submit:

`aztk spark cluster submit --id sparky --name pythonpi pi.py`

I'm at commit:

`commit 1d9d9cabb90ad1b896b40972e27d2bd55429d1ff`

Bug: fix loading local spark config (#282)

**Comment by jafreck** [comment]
This error means that somewhere along the way the container exited, so no submits will work.

If the cluster is still around,  you should be able to log onto the host to get the docker logs. From there debugging should be a little easier.

To get those logs, you would need to run:
`aztk spark cluster ssh --id <cluster-id> --username <username> --host`

If you don't have a user, you can create one with:
`aztk spark cluster add-user --id <cluster-id> --username <username>`

Then, once you are ssh'ed into the node, you can get logs by running:
`sudo docker logs spark`

**Comment by willferreira** [comment]
Here is the log output:

`sudo docker logs spark
Starting setup using Docker
Collecting azure-batch==3.0.0 (from -r /batch/startup/wd/requirements.txt (line 1))
  Downloading azure_batch-3.0.0-py2.py3-none-any.whl (281kB)
Collecting pyyaml==3.12 (from -r /batch/startup/wd/requirements.txt (line 2))
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting azure-nspkg>=2.0.0 (from azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading azure_nspkg-2.0.0-py2.py3-none-any.whl
Collecting msrestazure~=0.4.7 (from azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading msrestazure-0.4.19-py2.py3-none-any.whl
Collecting azure-common~=1.1.5 (from azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading azure_common-1.1.8-py2.py3-none-any.whl
Collecting msrest~=0.4.17 (from msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading msrest-0.4.22-py2.py3-none-any.whl
Collecting adal~=0.4.0 (from msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading adal-0.4.7-py2.py3-none-any.whl (49kB)
Collecting keyring>=5.6 (from msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading keyring-10.5.1-py2.py3-none-any.whl
Collecting requests-oauthlib>=0.5.0 (from msrest~=0.4.17->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading requests_oauthlib-0.8.0-py2.py3-none-any.whl
Collecting isodate>=0.5.4 (from msrest~=0.4.17->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading isodate-0.6.0-py2.py3-none-any.whl (45kB)
Collecting requests~=2.14 (from msrest~=0.4.17->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting certifi>=2017.4.17 (from msrest~=0.4.17->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
Collecting PyJWT>=1.0.0 (from adal~=0.4.0->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading PyJWT-1.5.3-py2.py3-none-any.whl
Collecting python-dateutil>=2.1.0 (from adal~=0.4.0->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
Collecting cryptography>=1.1.0 (from adal~=0.4.0->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading cryptography-2.1.4-cp35-cp35m-manylinux1_x86_64.whl (2.2MB)
Collecting secretstorage; sys_platform == "linux2" or sys_platform == "linux" (from keyring>=5.6->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading SecretStorage-2.3.1.tar.gz
Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.5.0->msrest~=0.4.17->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading oauthlib-2.0.6.tar.gz (127kB)
Collecting six (from isodate>=0.5.4->msrest~=0.4.17->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests~=2.14->msrest~=0.4.17->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
Collecting idna<2.7,>=2.5 (from requests~=2.14->msrest~=0.4.17->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests~=2.14->msrest~=0.4.17->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.1.0->adal~=0.4.0->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading cffi-1.11.2-cp35-cp35m-manylinux1_x86_64.whl (419kB)
Collecting asn1crypto>=0.21.0 (from cryptography>=1.1.0->adal~=0.4.0->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.1.0->adal~=0.4.0->msrestazure~=0.4.7->azure-batch==3.0.0->-r /batch/startup/wd/requirements.txt (line 1))
  Downloading pycparser-2.18.tar.gz (245kB)
Installing collected packages: azure-nspkg, oauthlib, certifi, urllib3, idna, chardet, requests, requests-oauthlib, six, isodate, msrest, PyJWT, python-dateutil, pycparser, cffi, asn1crypto, cryptography, adal, secretstorage, keyring, msrestazure, azure-common, azure-batch, pyyaml
  Running setup.py install for oauthlib: started
    Running setup.py install for oauthlib: finished with status 'done'
  Running setup.py install for pycparser: started
    Running setup.py install for pycparser: finished with status 'done'
  Running setup.py install for secretstorage: started
    Running setup.py install for secretstorage: finished with status 'done'
  Running setup.py install for pyyaml: started
    Running setup.py install for pyyaml: finished with status 'done'
Successfully installed PyJWT-1.5.3 adal-0.4.7 asn1crypto-0.24.0 azure-batch-3.0.0 azure-common-1.1.8 azure-nspkg-2.0.0 certifi-2017.11.5 cffi-1.11.2 chardet-3.0.4 cryptography-2.1.4 idna-2.6 isodate-0.6.0 keyring-10.5.1 msrest-0.4.22 msrestazure-0.4.19 oauthlib-2.0.6 pycparser-2.18 python-dateutil-2.6.1 pyyaml-3.12 requests-2.18.4 requests-oauthlib-0.8.0 secretstorage-2.3.1 six-1.11.0 urllib3-1.22
Running main.py script
starting org.apache.spark.deploy.master.Master, logging to /home/spark-current/logs/spark--org.apache.spark.deploy.master.Master-1-b0ae1a9494814effa269d0d13e8f7e39000000.out
failed to launch: nice -n 0 /home/spark-current/bin/spark-class org.apache.spark.deploy.master.Master --host b0ae1a9494814effa269d0d13e8f7e39000000.0fn24to4wihuvlujvgxdb32sab.fx.internal.cloudapp.net --port 7077 --webui-port 8080 -h 10.0.0.4 --webui-port 8080
full log in /home/spark-current/logs/spark--org.apache.spark.deploy.master.Master-1-b0ae1a9494814effa269d0d13e8f7e39000000.out
Failed to copy /batch/startup/wd/conf/spark-env.sh
[Errno 2] No such file or directory: '/batch/startup/wd/conf/spark-env.sh'
Failed to copy /batch/startup/wd/conf/core-site.xml
[Errno 2] No such file or directory: '/batch/startup/wd/conf/core-site.xml'
Failed to copy /batch/startup/wd/conf/spark-defaults.conf
[Errno 2] No such file or directory: '/batch/startup/wd/conf/spark-defaults.conf'
copy /batch/startup/wd/jars/azure-storage-2.0.0.jar to /home/spark-current/jars/azure-storage-2.0.0.jar
copy /batch/startup/wd/jars/hadoop-azure-datalake-3.0.0-alpha2.jar to /home/spark-current/jars/hadoop-azure-datalake-3.0.0-alpha2.jar
copy /batch/startup/wd/jars/hadoop-azure-2.7.3.jar to /home/spark-current/jars/hadoop-azure-2.7.3.jar
copy /batch/startup/wd/jars/azure-data-lake-store-sdk-2.0.11.jar to /home/spark-current/jars/azure-data-lake-store-sdk-2.0.11.jar
Pool has no master. Trying to assign itself! (1/5)
Assignment was successfull! Node tvm-171039672_2-20171217t133653z is the new master.
Setting up as master.
Adding master node ip 10.0.0.4 to config file '/home/spark-current/conf/master'
Starting master with '/home/spark-current/sbin/start-master.sh -h 10.0.0.4 --webui-port 8080'
Traceback (most recent call last):
  File "/batch/startup/wd/main.py", line 18, in <module>
    run()
  File "/batch/startup/wd/main.py", line 12, in run
    install.setup_node()
  File "/batch/startup/wd/install/install.py", line 18, in setup_node
    setup_as_master()
  File "/batch/startup/wd/install/install.py", line 29, in setup_as_master
    spark.start_spark_master()
  File "/batch/startup/wd/install/spark.py", line 81, in start_spark_master
    start_history_server()
  File "/batch/startup/wd/install/spark.py", line 89, in start_history_server
    properties = parse_configuration_file(path_to_spark_defaults_conf)
  File "/batch/startup/wd/install/spark.py", line 184, in parse_configuration_file
    file = open(path_to_file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/spark-current/conf/spark-defaults.conf'`

**Comment by jafreck** [comment]
You are exactly right, #279 seems to be the issue you are having. I'm going to push a fix for this momentarily.

**Comment by jafreck** [comment]
Hi Will, I just merged a change that should fix this issue. Could pull the latest changes and let me know that this has been resolved?

**Comment by jafreck** [comment]
Closing, fixed in #288
