### ISSUE TITLE
get cluster command when cluster-id does not exist returns a type error (instead of simple error msg)

### ISSUE THREAD

**Issue by jiata** [Azure/aztk#289]
`spark cluster get` when id isnt valid should return a "cluster does not exist" error instead of a typeerror.

(relatively low priority)

**Comment by jafreck** [comment]
```
-------------------------------------------
The specified pool does not exist.
RequestId:8d0a9b7c-ea44-4343-86d1-4f3ebb8f9766
Time:2017-12-18T20:13:26.5770790Z
-------------------------------------------
```

This is what I see when I run `aztk spark cluster get --id fake-cluster-id`

Can you give steps to reproduce the typeerror?

**Comment by jiata** [comment]
sorry my mistake. it only happens when a cluster is being deleted. 

in other words, if a cluster is in the process of deletion, and you call a `get` on it, it will throw the error.

**Comment by jafreck** [comment]
Cool, found the bug. Will put out a fix soon.
