### ISSUE TITLE
Is it possible to list the blobs in a blob container?

### ISSUE THREAD

**Issue by willferreira** [Azure/aztk#298]
I have a large number of files in a number of blob containers. Is it possible to get a list of them, e.g. something like py.path(<path>).listdir() ?

**Comment by jafreck** [comment]
I'm not quite sure what your use case is. But in general, yes it is possible to list blobs in a container. You would need to use one of the Azure Storage SDKs to do so. For example, in python, you could do this:

```python
from azure.storage.blob import BlockBlobService
block_blob_service = BlockBlobService(account_name='myaccount', account_key='mykey')
generator = block_blob_service.list_blobs('mycontainer')
for blob in generator:
    print(blob.name)
```

If you are looking for a way to list AZTK specific blobs or something to that extent, then no, there is no way of doing so. Could your use case a little more?

**Comment by willferreira** [comment]
Thanks. That's what I'm looking for. I'll spend a bit more time looking at the sdk.

**Comment by jafreck** [comment]
No worries -- please reach out with any other issues or questions.
