### ISSUE TITLE
py4j.protocol.Py4JJavaError: An error occurred while calling o52.csv. : org.apache.hadoop.fs.azure.AzureException: Uploads to to public accounts using anonymous access is prohibited.

### ISSUE THREAD

**Issue by willferreira** [Azure/aztk#299]
Started to get this message today when writing Spark dataframes to the Blob store. Yesterday I was able to write to the store, so a bit surprised by this. Has anything changed overnight? Or can someone point me at anything I may have inadvertedly changed?

**Comment by jafreck** [comment]
There have not been any changes to master in the last 2 days. The error looks like an authentication issue with Blob itself. It is likely that you aren't authenticating with Blob successfully.

Authenticating to Storage is done in your secrets.yaml file and in your core-site.xml file if you configured it. Your best bet is to check there and see if there are any errors in your configuration/secrets.

**Comment by willferreira** [comment]
Thanks. I'll double check everything.

**Comment by willferreira** [comment]
I double-checked the `secrets.yaml` and `core-site.yaml` and they're both configured as expected with the correct keys (in fact I haven't changed them since they were first configured, and have successfully written to the Blob store). 

I also ran some code that uses `BlockBlobService`, and the same key as in the `secrets.yaml` file, and I was able to create a container and upload files to it. The problem seems to be when I try and write to the Blob from the master node, using Spark's `SQLContext.createDataframe()`. It looks like the keys are not being passed correctly when the cluster is created (or maybe when I submit the job)? 

Note that I can read data from the container in a worker node.

**Comment by jafreck** [comment]
What is the Access Policy for the container you are trying to write to?

**Comment by willferreira** [comment]
Currently it's Container, but I tried with Private, Blob and Container.

**Comment by jafreck** [comment]
I can confirm that I was able to reproduce the issue. I'm looking into it now.

**Comment by jafreck** [comment]
This is still being explored. I'll update as soon as it is resolved.

**Comment by willferreira** [comment]
This issue has gone away now.

**Comment by jafreck** [comment]
Great - glad you were able to get this fixed.

**Comment by rkbansal83** [comment]
@willferreira  did you do something specific to resolve this ? I am running into same issue

**Comment by rahulsohal** [comment]
@willferreira Can you please explain how you were able to get away with this issue.?
