### ISSUE TITLE
How to install packages on each node?

### ISSUE THREAD

**Issue by willferreira** [Azure/aztk#330]
I configured a script in `cluster.yaml` to try and install some packages on each node:

`installs.sh`:

```
#!/bin/bash

sudo /usr/bin/anaconda/bin/conda install -c anaconda pymongo
sudo /usr/bin/anaconda/bin/conda install -c conda-forge mongoengine
```

`custom_scripts`: 

```
    - script: ./installs.sh
       runOn: all-nodes
```

But my spark cluster job fails when trying to `import pymongo`. Is this the correct way to install additional packages?

**Comment by jafreck** [comment]
In general, yes this is the right way. However, there is an issue with the content of your script. 

First, `sudo` is not installed in the container. The script will be run as `root` so it is not necessary.

Also the path you have for `conda` does not match the path on the node. `conda` is on the PATH already, so you can just call it without an absolute path.

You should also add the `-y` flag to forgo confirmation.

So your script should look like this instead:

```
#!/bin/bash

conda install -c -y anaconda pymongo
conda install -c -y conda-forge mongoengine
```
