### ISSUE TITLE
Make driver always execute on the Spark master

### ISSUE THREAD

**Issue by jafreck** [Azure/aztk#375]

**Comment by jaley** [comment]
Just a quick not for clarification on this feature.

If we're making the driver and spark master run on the same machine, we might *not* want the spark worker service running on that node? I think that'd be a good configuration for our use cases in general, that there's one machine running the master and driver, but no worker service, and then on worker machines the worker service claims all resources.

There may be use cases where it makes sense to run the driver on a random worker node, and not claim all resources on every worker to accommodate that - such as if you're running multiple concurrent applications on the same cluster, and you don't need to *know* where your driver is running, I would guess. Our team doesn't have a use for that right now.

**Comment by jafreck** [comment]
Definitely agree that the option to run a worker on the master should be given.

**Comment by jafreck** [comment]
One of the things we will need here is a way to share the Batch task's working directory with the master node. We can use a tool like rsync but I think a cleaner solution might be to have HDFS installed on the cluster by default. Interested to know what other people think.

**Comment by jafreck** [comment]
Another option would be to handle the downloading of task resource files to the master node directly. Instead of using Batch's resource files, we could just download the files directly to the master node.
