### ISSUE TITLE
Jobs do not support both dedicated and low priority nodes

### ISSUE THREAD

**Issue by shtratos** [Azure/aztk#438]
I use `aztk` from current master: https://github.com/Azure/aztk/commit/bcefca3d2f13138b5135481972a212e80365edf4

### Creating mixed cluster for a job

I get this error message when trying to use mix of dedicated and low priority nodes in job cluster config:

```
2018-03-14  15:35:26: ERROR: Jobs do not support both dedicated and low priority nodes. 
JobConfiguration fields max_dedicated_nodes and max_low_pri_nodes are mutually exclusive values.
```

The error seems to originate here:
https://github.com/Azure/aztk/blob/2bed496c398c7c3860ad62b1ce7d9fc14ee299bb/aztk/spark/client.py#L201-L202

On the other hand, in the [Enable VNET](https://github.com/Azure/aztk/projects/3) project, the following item is marked as "Done":
> Allow users to create MixedMode clusters (specify dedicated and low-pri in the same cluster).
>
> - Master node should always be provisioned on a dedicated node.

### Creating mixed standalone cluster 

When I try to create a cluster from the following `cluster.yaml` file using `aztk spark cluster create --id pi-test1`,
```
#cluster.yaml
vm_size: standard_e4_v3
size: 2
size_low_pri: 2
username: spark
docker_repo:
wait: false
```
I get a cluster only with low priority nodes:

```
Cluster         pi-test1
------------------------------------------
State:          active
Node Size:      standard_e4_v3
Nodes:          2
| Dedicated:    0
| Low priority: 2

|               Nodes                |        State        |        IP:Port       | Dedicated  |  Master  |
|------------------------------------|---------------------|----------------------|------------|----------|
|tvm-1512202362_1-20180314t155215z-p |        idle         | 52.138.216.156:50000 |            |    *     |
|tvm-1512202362_2-20180314t155215z-p |        idle         | 52.138.216.156:50001 |            |          |
```

This behaviour seems to be caused by the following code:
https://github.com/Azure/aztk/blob/c237501a9f9ab20d213c8377956de1a2f8043570/aztk_cli/config.py#L154-L160

### Questions

- Can I create mixed clusters at all? 
 - What are the changes required to make jobs support mixed clusters?

**Comment by timotheeguerin** [comment]
Due to limitations cluster can only work with mixed mode if you have a subnet provided. Though It should throw you an error if you don't have it setup and try to use mixed mode so this sounds like a bug. [Doc for mixed mode](https://github.com/Azure/aztk/blob/master/docs/10-clusters.md#mixed-mode)

For job submission we don't support it yet though it shouldn't be a big change to enable now

**Comment by shtratos** [comment]
@timotheeguerin Thank you for the link

Yeah, I got the error:
> You must configure a VNET to use AZTK in mixed mode (dedicated and low priority nodes). Set the VNET's subnet_id in your cluster.yaml

after I hacked config not to set ` output.vm_count = 0`
https://github.com/Azure/aztk/blob/c237501a9f9ab20d213c8377956de1a2f8043570/aztk_cli/config.py#L158-L160

Let me try this with a subnet.

**Comment by shtratos** [comment]
Thanks, adding a subnet worked for the standalone cluster.

Now I'm trying to do the same with the jobs.

I've replaced this
https://github.com/Azure/aztk/blob/2bed496c398c7c3860ad62b1ce7d9fc14ee299bb/aztk/spark/client.py#L192-L202

with 
```python
            autoscale_formula = "$TargetDedicatedNodes={0}; $TargetLowPriorityNodes={1}".format(
                    job_configuration.max_dedicated_nodes, job_configuration.max_low_pri_nodes
            )

```

But now the job is stuck in "Cluster provisioning" state for about 25 minutes:

```
$ aztk spark job get --id test-job-3
Job               test-job-3
------------------------------------------
State:            active
Transition Time:  17:23PM 14/03/18

Cluster                             | Provisioning

Applications
------------------------------------------
scheduling:       1

No Spark applications will be scheduled until the master is selected.
```

**Comment by jafreck** [comment]
There is some extra configuration checks that are required to support mixed mode with Jobs. I put this on the backlog for the next release, so you can expect it soon.

**Comment by timotheeguerin** [comment]
if the cluster is stuck provisioning it probably means the master wasn't elected because something failed in the start task. To see that you go check the files `startup/stderr.txt` and `startup/wd/logs/docker.log` on one of the nodes with BatchLabs or the Azure Portal

**Comment by jafreck** [comment]
@timotheeguerin I'm actually seeing the same bug, but it appears to be because the cluster is not being created at all. The job schedule and job are active, with a autopool spec that looks right, but no cluster is created. I'm investigating.

**Comment by shtratos** [comment]
Was the cluster provisioning issue caused by the `enable_node_intercommunication` flag?

**Comment by jafreck** [comment]
Yes, that was the issue. Batch requires that pools created with both dedicated and low priority nodes have that flag disabled. 

It was interesting that the service did not throw an error when this was done by way of an autopool created through a job schedule. I believe that should not be allowed.

**Comment by shtratos** [comment]
Yeah, sounds like a bug. 

Thanks a lot for fixing this so fast! Much appreciated. I'll try submitting the job again on Monday.
