### ISSUE TITLE
History server doesn't start

### ISSUE THREAD

**Issue by jaley** [Azure/aztk#452]
The spark history server doesn't appear to be running on the master instance at port 18080, as the splash screen suggests when a cluster is created.

I managed to get it to start on an already-running cluster by setting `spark.history.fs.logDirectory` to `/mnt/batch/spark-events` (event logs can get quite big, `/tmp` will likely fill up on a big job), and making the target directory before running the init script in `$SPARK_HOME/sbin`

Update: You actually also need to enable logging to the same location in the app itself to use the history server. The following configuration worked well for me:

```
spark.history.fs.logDirectory     /mnt/batch/tasks/spark-events
spark.eventLog.dir                /mnt/batch/tasks/spark-events
spark.eventLog.enabled            true
spark.eventLog.compress           true
```

**Comment by jafreck** [comment]
@jaley  glad you were able to resolve the issue. You do need both `spark.eventLog.dir` and `spark.eventLog.enabled` set to have history server started.

**Comment by jaley** [comment]
@jafreck - those are required to make the submitted spark application write events to the event log directory. I'm *also* finding that the history server itself is not running. If I ssh to the master instance, there's no sign of it, and nothing in the logs folder initially. Running `sbin/start-history-server.sh` will produce an error, because the configured events directory doesn't yet exist. It works fine if I make the directory manually then start it.

Could it be that I'm using a `.aztk./` folder template generated from an older version?

**Comment by jafreck** [comment]
I see, thanks for clarifying. I'll investigate.

I doubt it is because of your `.aztk/` folder, although regenerating with the newest version would not hurt to try.

**Comment by jafreck** [comment]
It looks like `spark.history.fs.logDirectory` and `spark.eventLog.dir` are necessary for history server to function as expected, just like you found. I put a pr out to require both (previously only `spark.eventLog.dir` was required). We will ship with defaults that work, so when you run `aztk spark init` history server will work out of the box if enabled.

I also see we have absolutely no docs on how to run history server so I'll fix that as well.

**Comment by jaley** [comment]
So, is the expectation that the user will run the `sbin/start-history-server.sh` script manually from the master instance if they want history? I was confused, because when you ssh into the master, the green text printed to the console kind of implies that it's already running on port 18080, and indeed the port forwarding is already running, there's just nothing listening on the other end.

Also, now that I think about it... this task probably depends on #375 in order to be useful. The history server works by processing event logs written to a file by driver applications to those paths we configured above, which it seems need to be local paths (maybe?). So, if the driver wrote its event log to a local path on a different machine to the history server, you'll probably just see any empty history in the UI.

To be honest, I think the simplest configuration where everything "just works" for most users would be that the master instance has Spark Master & Spark History Server already running, plus it'll run any submitted driver applications. Task instances run the Spark Worker service plus Spark Shuffle service. That'll make for a setup where all services are working, and the CPU/memory intensive jobs are not interfering with utility/monitoring/coordination jobs. I think it's also possible to proxy access to the worker UIs for logs through the master, so that'll mean an SSH tunnel to the master can serve as a single port of call for users to access all UIs.

I mentioned in the other ticket that a user could conceivably want multiple drivers contending for the same cluster. I expect it's an edge case in a (almost) SaaS like product, as it's just as easy to bring up multiple clusters for multiple jobs. In any case, I'd expect coordinating multiple drivers running on the master to be easier than scaling back the worker service on a randomly selected node?

**Comment by jafreck** [comment]
The expectation for the user will just be that they have the proper settings in their `spark-defaults.conf`. History server should be started automatically for them if the necessary values are found. We should also only show the history-server link if it is running (I added that to the backlog #458).

#375 would definitely make history server work out of the box as expected, however, it is not absolutely necessary. If you wish, you can enable the HDFS plugin, and write your logs there (set `spark.history.fs.logDirectory`, and `spark.eventLog.dir` to hdfs paths). Then history server will pick up all application logs from all nodes. You could also use any other HDFS API compliant storage service like WASB.

As far as the Spark UI goes, we are actively looking for ways to make that fully operational through just a single ssh tunnel. We have a proxy tool in the works that should be available relatively soon. We also are looking to add a VPN plugin.

I'm not quite sure I understand your last point. It's possible today to have multiple drivers on the same cluster (though there are limitations imposed by the Batch service). Today you can run as many drivers as there are nodes in the cluster. We have a workitem to raise this limit, though. Could you explain what you mean by you "expect coordinating multiple drivers running on the master to be easier than scaling back the worker service on a randomly selected node." Do you mean that if you knew the driver always executed on the master, you wouldn't have to worry about competing for resources with workers?

**Comment by jaley** [comment]
OK, thanks for explaining, that makes more sense. I didn't get that aztk will only start the history server if it's enabled in `spark-defaults.conf`. I *think* I've submitted jobs with those config parameters already set, and didn't see a history server already running, but I'd need to double check that. 

One slight snag there is that there's theoretically no reason a user would be using the same spark configuration for every application they submit to a single cluster - some may have history enabled, others may not. The `--conf` parameter to `spark-submit` will allow them to override on a per-application basis. Whether or not the service is running will be fixed for the lifetime of the cluster, I would assume, so they would see different behaviour depending on whether they set configuration in `spark-defaults.conf` when the cluster was created vs at app submission time. For us, this is no big deal, as we use aztk specifically because it allows us to create single-purpose clusters and tear them down when we're done, and I expect that caveat could just be documented to help others.

On that last point - yes, exactly. IIUC, Aztk (or Batch?) is picking a node at random to run the driver on, eventually running `spark-submit` from somewhere in the node scripts, on that random node, without making any changes to the `--deploy-mode` parameter? At least, grepping the codebase, I can't find any reference to it :-)

The default deploy mode is "client", which means the driver will run as a local JVM, as a child process of that `spark-submit` script. This makes it tricky to configure the cluster optimally because we have to set the same spec for all worker instances. Any *one* of them could be picked to run that driver, so *all* of them must have adequate spare capacity to do it, as driver applications can get pretty hefty themselves. You're therefore not making use of the whole cluster, as N-1 workers have spare space for the driver that never got scheduled to them.

I think the "cluster" deploy mode is meant to avoid this, as the driver will be scheduled to run from the pool of resources available from the existing worker agents on the cluster that way. It means you can run `spark-submit` anywhere, but the master will pick a worker to run the driver out of its pool of worker resources, so that it then knows not to schedule so many executors to that particular instance when the app requests them.

That deploy mode is presumably intended for multi-tenant, shared clusters, which as I've mentioned before, we don't have much of a use case for right now, but for those that do, I think using "cluster" deploy mode makes better use of resources. For us, it makes more sense to utilise the spare capacity on the master by just running `spark-submit` in "client" mode from the master.

(It's possibly I misinterpreted the code in the node scripts and missed the part where we set the deploy mode - if so apologies and nevermind!)

**Comment by jafreck** [comment]
If you aren't seeing history server up even with those settings in `spark-defaults.conf` we likely have a bug somewhere. I'll continue to test to see if I can reproduce that issue.

Having different spark configurations per application is fine, but I see how it might be confusing when some of the configuration is tied to cluster lifetime, not application lifetime (i.e. an autostarted history server). For now, the spark configuration you submit at cluster creation time will control whether history server, for example, is started. Applications don't (currently) have the ability to specify another spark configuration with which they are run except in code. This is a possible feature we can consider.

As far as deploy modes go, we have considered "cluster" in the past, and are open to the idea of switching if it better matches user's use cases. We have also considered guaranteeing that the driver run on the master (#375). We need to investigate more to understand what level of control we should expose to users for the driver application. Your point about "cluster" mode being more aware of resource utilization from Spark's perspective is well taken, as is your point about driver-always-on-master allowing a more clear understanding of resource utilization from a users standpoint. We will have to discuss which (or all) of these is the right solution, but it is definitely on our roadmap.

**Comment by shtratos** [comment]
@jafreck I'd love to see instructions on how to configure Spark History server that uses WASB for storage.

I run Spark jobs on one-off clusters, but I still want to keep application logs and stats to see how running times and memory usage vary over time.

**Comment by jafreck** [comment]
@shtratos Using WASB for storage requires three things:
1. Setting your credentials in `core-site.xml`. The default `core-site.xml` comes with commented out instructions for how to do this. 
2. Setting the path for `spark.eventLog.dir` in `spark-defaults.conf` to a WASB blob storage path that exists (for the storage account you gave credentials for in `core-site.xml`)
3. Setting the path for `spark.history.fs.logDirectory` in `spark-defaults.conf` to the same WASB path

WASB paths are of the form `wasb[s]://<containername>@<accountname>.blob.core.windows.net/<path>` so your `spark-defaults.conf` would have a block like this:

```sh
spark.eventLog.enabled            true
spark.history.fs.logDirectory     wasbs://my_container@my_account.blob.core.windows.net/my_logs
spark.eventLog.dir                wasbs://my_container@my_account.blob.core.windows.net/my_logs
```

**Comment by mmduyzend** [comment]
We tried using WASB for persisted history log storage as per the above instructions, but it did not work: A 0B `.inprogress` file appeared at the blob storage path while the job was running, but the application then hung after all stages of the job were complete. We left it overnight, but the application did not terminate and no actual logs were written to blob storage.

This was a relatively small job, and the blob container was in the same region as the aztk cluster, so it is unlikely that the problem was due to the time required for data transfer. The `.inprogress` file suggests that there was no problem with write access to the blob storage.

If I run the same application with all the same settings save for using a local path rather than WASB for persisted history server log storage, it works fine. But we would like to use WASB so we don't lose the logs when we tear down one-off clusters. Any idea what could be going wrong?

**Comment by jafreck** [comment]
I'll investigate and see if I can reproduce this.

**Comment by jafreck** [comment]
@mmduyzend I just spun up a cluster with the setting settings in `spark-defaults.conf` described above, and I can see history server is running on the cluster, with application logs being shown as expected. In my storage account, I see the app logs are present as well.

I agree that the `.inprogress` file suggests that authentication & authorization to storage is working.

I'm at a bit of a loss here since I can't reproduce the issue. When you say the application hung, do you mean the spark application or the aztk application? Do you know whether the spark app completed successfully?

**Comment by jafreck** [comment]
Reclosing since I cannot reproduce this. Let me know if the issue persists.
