### ISSUE TITLE
I only see master node running, how can I force my app to run on multiple nodes

### ISSUE THREAD

**Issue by saroup** [Azure/aztk#460]
Hi there, 
 I have created a vm_size="standard_f2" and vm_count = 4 and used the sdk_example.py to submit my job.
When I run it and check the status of my cluster I only see the master node in running state and all the others are idle. 
In the submit code affinitize_task_to_master is called which makes the job start on master. But what should make it run on the other nodes as well?
I am running into out of memory issues and I suspect this to be a factor in it.

Thanks!

**Comment by jafreck** [comment]
Even though only one node is in the "running" state, all nodes in the cluster will be used. The "running" state just refers to which node is running the Spark driver application.

You can look at the Spark master UI (`aztk spark cluster ssh` into the cluster, and navigate to localhost:8080) to verify that you have the expected number of workers.

As far as the running out of memory issues, you might need to play with the application settings for driver-memory and/or executor-memory to raise from Spark's default 1G.

**Comment by saroup** [comment]
Thanks @jafreck  for your quick reply!

1. When I do aztk spark cluster ssh -id myclusterid it tells me that 'ssh' is not recognized as an internal or external command and when I go to localhost:8080 it cannot find the page.
2. As for the memory allocation I have tried to increase the memory of my driver and executor to 4g and 8g but now I am getting this error: "Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources" 
and basically my app is taking forever.

Any suggestions?

**Comment by jafreck** [comment]
For SSH to work, you need an ssh client installed on your local machine. I'm assuming you are on Windows. If so, here is a tutorial for you to download and install [OpenSSH for Windows](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH).

The error you are seeing appears when the cluster does not have enough resources to run the application. This can happen if say, you have a cluster of nodes that each have 2G of memory, and you submit an app with `executor-memory` set to 3G. In that case, the cluster has insufficient resources to run the job as submitted, so the application sits in a waiting state and never runs. To fix this, ensure your cluster has the necessary resources.

**Comment by saroup** [comment]
for the cluster config I am using vm_size="standard_f2" which has 4Gb of RAM and my vm_count is 2.
I have set the driver_memory and executor_memory to 9g but I am still getting the same error message 

"Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources"

**Comment by jafreck** [comment]
`executor-memory` is set on a per node basis since an executor runs on each of your nodes. If you have a node with 4G RAM and set `executor-memory` to 9G, the app will never run.

Here is some of Spark's documentation on configuration settings for applications: https://spark.apache.org/docs/latest/configuration.html#application-properties
That should provide better insight into the relevant settings.

For now, I'm going to close this issue since this is not an AZTK bug. However, feel free to continue to reach out on this thread if you need more assistance.

**Comment by saroup** [comment]
Thanks for your help!
I don't understand what you are trying to say here or I am obviously missing something.
I am giving each node 9G of memory while it only needs 4G why would my app never run?

**Comment by saroup** [comment]
Okay now I understand what you mean. executor_memory is setting how much memory my app will need to run so I have to make sure each node has at least that amount of memory.

**Comment by saroup** [comment]
I set executor-memory to 3gb and I have 2 nodes of 4gb each. 
However, I still hit the same problem. 
"ExecutorAllocationManager: Requesting 1 new executor because tasks are backlogged (new desired total will be 1 Initial job has not accepted any resources..."
@jafreck do you think this can be related to another issue?

**Comment by jafreck** [comment]
Exactly -- `executor-memory` defines the minimum amount of memory that each executor must use to execute your application. So it must be less than the total amount of memory each node has.

For the new issue, what are you setting `driver-memory` to?
