### ISSUE TITLE
--docker-repo command line argument no-longer works

### ISSUE THREAD

**Issue by lachiemurray** [Azure/aztk#537]
The docker-repo command line argument no-longer works. The following command will complete without error but it will create a cluster with the default image (unless "docker_repo" is changed in .aztk/cluster.yaml):

`aztk spark cluster create --id <cluster_id> --size <cluster_size> --docker-repo <private_docker_repo>`

Not sure if this is supposed to work anymore or if it was deliberately removed. If it was deliberately removed then the corresponding argument should also be removed so that the above command will fail:

https://github.com/Azure/aztk/blob/4d4916e349acee4d1b2d32a260b417247eed03e7/aztk_cli/spark/endpoints/cluster/cluster_create.py#L24

**Comment by timotheeguerin** [comment]
This seems to be an issue coming from the new toolkit definition. Thinking of that we should also maybe add a way to define the toolkit from cli args
