### ISSUE TITLE
Installing Aztk breaks NodeJS installation

### ISSUE THREAD

**Issue by josefarinna** [Azure/aztk#598]
Hello,

I was trying to install in the same machine NodeJS (8 or 10) and aztk, but if I install aztk and then NodeJS, aztk gets corrupted, but if I do in the opposite order, NodeJS gets corrupted.

Any suggestions on how to install both without issue?

I'm using an Azure Standard A0 with Ubuntu 16.04 LTS machine.

Regards.

**Comment by timotheeguerin** [comment]
What do you mean by corrupted? Could you share some logs of the errors.

Also could you let us know how you installed aztk and node?

**Comment by josefarinna** [comment]
Now seems that is working fine, after creating and removing the machine several times and using the same commands, seems that now is workings, its extrange, but working.

Sorry for the inconvenience.
