### ISSUE TITLE
debug cluster - unusable state

### ISSUE THREAD

**Issue by cbenitomonje** [Azure/aztk#623]
Hi,

I´m trying to debug my cluster with command :  **aztk spark cluster debug --id sparkcluster --output logsAztk/**

It creates the file in the specific folder but it´s not able to write anything in the "debug-output.txt" file. ( i already tried with sudo command)

I´m using 0.8.1 Aztk version.

This is the error: 

![image](https://user-images.githubusercontent.com/26383270/42274546-5fa102a6-7f8d-11e8-90d9-642114f00f0f.png)

Thanks.

**Comment by jafreck** [comment]
Just to be clear -- every node in the cluster is in an unusable state when this error occurs?

**Comment by cbenitomonje** [comment]
Yes, all the nodes are unusable.

Thank you.
