### ISSUE TITLE
update aztk/examples/sdk/sdk_example.py

### ISSUE THREAD

**Issue by saroup** [Azure/aztk#627]
sdk_examply.py seems to be outdated and doesn't reflect the changes that happened in 0.8.0.
The ClusterConfiguration doesn't have a toolkit associated and the script is still using custom scripts which are deprecated for this version.
I find this file very relevant to get started with aztk so we should consider updating it.

**Comment by saroup** [comment]
it looks like the toolkit has been added but custom scripts are still there

**Comment by jafreck** [comment]
Agreed -- this needs to be updated and will be taken care of as a part of #622.
