### ISSUE TITLE
rename --webui to --jobui and rename --masterui to --webui in cli

### ISSUE THREAD

**Issue by jiata** [Azure/aztk#63]

**Comment by jiata** [comment]
@jafreck if/when you get around to doing the .ssh config feature #75 - do you think it'd be possible to just lump this into the same PR?

**Comment by jafreck** [comment]
yeah, sure

**Comment by jafreck** [comment]
Still need to rename variables and constants [here](https://github.com/Azure/aztk/blob/37c5d873a037449c06929cdaf16260cf6088d2d4/aztk/clusterlib.py#L465).
