### ISSUE TITLE
Aztk spark submit using only master node

### ISSUE THREAD

**Issue by cassar1** [Azure/aztk#631]
Hi there,
I have created a cluster with 3 nodes low priority standard_d1_v2
When I run a task using submit and check the status of my cluster I only see the master node in running state and all the others are idle. Additionally even when using ssh to check the job status or history through Spark UI and Spark history UI, only the executor driver is being added to the task (from the Spark UI event timeline). 

SparkUI executors tab also shown one executor - being the driver. 

![event timeline](https://user-images.githubusercontent.com/6871647/43580994-96bd0fec-9657-11e8-9960-a16c05ec596b.JPG)

Nonetheless, spark does seem to have the visibility of all the nodes as it shows 2 workers that are not being used, it simply seems that they are not being called for the task.

![workers](https://user-images.githubusercontent.com/6871647/43581006-9d5deba0-9657-11e8-9ceb-1102edb77e4a.JPG)

Any help please ?

Thanks!

**Comment by jafreck** [comment]
It is expected that only one node will be in a "running" state and that is the node that will run the driver.

As far seeing an unexpected amount of executors, this is possible, but is dependent on the nature of the spark application being submitted. If the master ui shows that all nodes are registered and alive in the cluster, as your second screenshot shows, then the cluster is in a functional state.

**Comment by jafreck** [comment]
I'm going to close this as I do not believe this is a bug, but feel free to reach out if you find anything else!

**Comment by shinen** [comment]
However, even when I switched worker nodes to offline state, executors can still be added to these worker nodes. 
This does not seem to be normal?
