### ISSUE TITLE
Updates to transitive dependencies are incompatible

### ISSUE THREAD

**Issue by jafreck** [Azure/aztk#638]
The current dependencies in setup.py have incompatibilities in the dependency tree.

Both `msrestazure` versions ~=0.4.11 and 0.5.0 are required.

An update to `azure-mgmt-batch`, `azure-storage-blob`, and `azure-mgmt-storage` resolves this issue.

**Comment by shtratos** [comment]
Maybe adopt `pipenv`? https://docs.pipenv.org/
It solves the problem of non-fixed dependency versions.

**Comment by jafreck** [comment]
pipenv is great for locking down the entire dependency tree. However, the project makes a distinction between a library (code that is published and reused) and an application (code that is to be deployed to a specific environment, and not depended on by other projects). pipenv only caters to applications, not libraries. Aztk falls into the library category since it has an SDK (and we publish to pip using the standard python tooling).

So unfortunately, pipenv just doesn't work for our use case. We do, however, use pipenv in aztk today for the code deployed on the Azure Batch compute nodes. That code falls into the application category as it is deployed on a specific environment (Batch) and needs to be reproducible. In that case, we get the benefits of locking the entire dependency tree.

The unfortunate end result of this is if any of our direct or transitive dependencies do not correctly specify versions or break semantic versioning, we will get broken for new installs. This seems to be a universal python library issue, though.

**Comment by shtratos** [comment]
While AZTK SDK is a library, AZTK CLI on the other hand is an application.

I've recently encountered version conflicts installing AZTK CLI from older commit via `pip install -e .`.
IMO this could have been avoided if project contained `Pipenv.lock`.

Of course, the obvious workaround is for AZTK clients to use `pipenv` themselves. But that's an extra step.

**Comment by shtratos** [comment]
Oh, I noticed there is `requirements.txt` in the project root. I guess I should first install them before installing `aztk`.
