### ISSUE TITLE
Cluster.visible_state not set correctly

### ISSUE THREAD

**Issue by jamesclarke** [Azure/aztk#670]
I believe that the following line contains a bug and will never be `True`:
https://github.com/Azure/aztk/blob/b7da355618173c15d277b458a7e1fe10e3273c8c/aztk/models/cluster.py#L10
since `pool.state.value` is of type `str` and `batch_models.PoolState.active` is of type `<enum PoolState>`.

I think this line was meant to read:
```python
if pool.state is batch_models.PoolState.active:
   ...
```

I discovered this when examining a `Cluster` object in a REPL:
```python
In [32]: cluster.visible_state
Out[32]: 'active'

In [33]: cluster.pool.state
Out[33]: <PoolState.active: 'active'>

In [34]: cluster.pool.allocation_state
Out[34]: <AllocationState.resizing: 'resizing'>
```
and think that the intended logic of the code was to have the following result:
```python
In [32]: cluster.visible_state
Out[32]: 'resizing'
```

**Comment by jafreck** [comment]
You are correct, that line will always be false. Thanks for reporting!
