### ISSUE TITLE
Contain the pools within a VNET completely.

### ISSUE THREAD

**Issue by ana1993** [Azure/aztk#702]
Currently, when I create mixed-mode pools, I see the nodes are getting public IP addresses(The docker container getting spawned gets a IP within the specified VNET) even though my use case does not require it to be accessible on an open network. A feature will be useful to have the nodes get an address on the provided VNET so that no public IP addresses are created.

**Comment by jafreck** [comment]
Azure Batch (which Aztk runs on) will automatically allocate 1 Public IP per 50 nodes in the Cluster (Batch Pool). The network can be locked down if the Aztk Cluster is created with a Subnet. You can configure your subnet with Network Security Group rules to control network access as necessary.

**Comment by jafreck** [comment]
Closing as this is a limitation of Batch, and cannot be fixed by Aztk.
