### ISSUE TITLE
aztk cluster spinup failure

### ISSUE THREAD

**Issue by ImNaman** [Azure/aztk#715]
Hello @jafreck  @timotheeguerin 
Startup tasks of all nodes are failing with the following error - 

Finished pulling aztk/spark:v0.1.0-spark2.2.0-base
real	0m0.166s
user	0m0.023s
sys	0m0.022s
Node python version:
Python 3.5.2
Collecting pip==18.0
  Downloading https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl (1.3MB)
Collecting distlib<1,>=0.3.0 (from virtualenv->pipenv==2018.7.1)
  Downloading https://files.pythonhosted.org/packages/7d/29/694a3a4d7c0e1aef76092e9167fbe372e0f7da055f5dcf4e1313ec21d96a/distlib-0.3.0.zip (571kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools

FYI, a month ago I was using the same setup to spin up clusters.

**Comment by jafreck** [comment]
Hi, can you please update to the latest version of aztk (v.0.10.3): https://pypi.org/project/aztk/0.10.3/

There was a known issue that caused this failure (#710). The latest release has the fix.

**Comment by ImNaman** [comment]
@jafreck Upgrading to the latest version worked for me! Thanks a lot
