### ISSUE TITLE
start task failed

### ISSUE THREAD

**Issue by SidWeng** [Azure/aztk#716]
AZTK submit job works fine until this morning, and I found following error in startup/stdout.txt.
I believe the root cause is as same as #710 .

```
Installing python dependencies
Creating a virtualenv for this project...
Pipfile: /mnt/batch/tasks/startup/wd/.aztk-env/Pipfile
Using /usr/bin/python3.5m (3.5.2) to create virtualenv...
ImportError: cannot import name 'ContextManager'

Virtualenv location: /mnt/batch/tasks/startup/wd/.aztk-env/.venv
Creating a virtualenv for this project...
Pipfile: /mnt/batch/tasks/startup/wd/.aztk-env/Pipfile
Using /usr/bin/python3 (3.5.2) to create virtualenv...
ImportError: cannot import name 'ContextManager'
```

**Comment by SidWeng** [comment]
cannot importlib-resources 1.1.0, should use importlib-resources 1.0.2, add this line in setup_host.sh.
```
python3 -m pip install importlib-resources=="1.0.2"
```

**Comment by jafreck** [comment]
Can you share which version of `aztk` you are using?

**Comment by SidWeng** [comment]
0.10.2

**Comment by jafreck** [comment]
This can no longer be reproduced. The issue appears to have been resolved by an update to a transitive dependency. @SidWeng can you confirm that this is no longer impacting?
