### ISSUE TITLE
Change print text after cluster create command so that it doesn't say "cluster created successfully"

### ISSUE THREAD

**Issue by jiata** [Azure/aztk#78]
Gotten feedback that this is a confusing message - conceptually it is correct (cluster of 0 nodes is created), but it is confusing. Instead it should say "You cluster is being created" something like that.

**Comment by jafreck** [comment]
Shouldn't we have different messages depending on if the --wait flag is flipped or not. So "Cluster created successfully" appears if the wait flag is set, and "Cluster being created" appears if the flag is not set.

**Comment by jafreck** [comment]
Also, after #65 is merged, you can't create a cluster of 0 nodes anymore.
