### ISSUE TITLE
[azb spark cluster create --id my_cluster --no-wait] unexpected behavior

### ISSUE THREAD

**Issue by jiata** [Azure/aztk#98]

**Comment by jiata** [comment]
When i install the package and run: "azb spark cluster create --id cluster --no-wait", it will wait anyway. My guess is because i didn't specify a username, and so it uses the default username in the config. However, having a username means that --wait needs to be true.

How should we handle this.

**Comment by jafreck** [comment]
The intended behavior if a username is specified and wait is set to false is to throw an error to let the user know that this configuration won't have the expected outcome.

I'll look into this to see why "--no-wait" isn't overwriting.
